### ISSUE TITLE
Output file contains a temporary string

### ISSUE THREAD

**Issue by vijinpaulraj** [tadayosi/parcel-plugin-concat#2]
Hi - I'm trying parcel-plugin-concat to build my project with multiple entry files and everything seems to be working fine. The only issue is, the output file generates a random/temporary string in the suffix. As I include output.js in the index.html file, I want this exactly to be output.js. Is this something that can be fixed in the plugin?

`parcel build src/js/* -o output.js --out-dir public/js`

![image](https://user-images.githubusercontent.com/14046103/97096559-bcc92300-165d-11eb-9575-00ca2f7de320.png)

**Comment by tadayosi** [comment]
Thanks for the report. I noticed the issue; even with `--no-content-hash` parcel adds the content hash. Let's see if we can fix it.

**Comment by tadayosi** [comment]
@vijinpaulraj In fact the `--no-content-hash` parcel option does what you want. It still includes a hash in the output file, but it should be always the same as the hash is caculated based on the output path rather than the content. You are free to change `output.<hash>.js` to `output.js` afterwards. See: https://github.com/parcel-bundler/parcel/pull/1934#issuecomment-546686161

**Comment by vijinpaulraj** [comment]
Thanks, @tadayosi for coming back on this.

The problem is, if I want to make a build for production, the renaming bit will be quite challenging - perhaps I need to write a script to rename the output file.

**Comment by tadayosi** [comment]
@vijinpaulraj With `--no-content-hash` the output file name should be always the same, so if you use npm scripts you can easily rename it as follows:
```js
  "scripts": {
    ...
    "postbuild": "mv public/js/output.xxxxxxxx.js public/js/output.js"
  }
```
or you can use `output.xxxxxxxx.js` as-is at client as the hash code shouldn't change.
